### PR TITLE
fix: handle results that can't be mapped to the changeset in bulk_create

### LINKED ISSUE #637: Ash.bulk_create/4 returns empty list records when using integer primary keys
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### AI Policy

- [x] I agree to follow this project's AI Policy, or I agree that AI was not used while creating this issue.

### Versions

elixir 1.18.3
erlang 27.3
ash 3.6.2
ash_postgres 2.6.22

### Operating system

mac

### Current Behavior

Starting from ash_postgres 2.6.22, calling Ash.bulk_create/4 returns empty list records even when the insert actually succeeds in the database.

This regression seems related to the following commit:
https://github.com/ash-project/ash_postgres/commit/af0903f1380468bbe1b61fe65acb33772b5e24a5

From the code changes, it appears that the new identity-based result matching logic introduced in this commit fails when the primary key is integer-based (auto-increment), since the key is not present in the input changesets.

### Reproduction

_No response_

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by barnabasJ**
should fix #637 

# Contributor checklist

Leave anything that you believe does not apply unchecked.

- [x] I accept the [AI Policy](https://github.com/ash-project/.github/blob/main/AI_POLICY.md), or AI was not used in the creation of this PR.
- [x] Bug fixes include regression tests
- [ ] Chores
- [ ] Documentation changes
- [ ] Features include unit/acceptance tests
- [ ] Refactoring
- [ ] Update dependencies

### CODE REVIEW

File: lib/data_layer.ex [hunk 1]
```diff
@@ -2120,35 +2120,63 @@ defmodule AshPostgres.DataLayer do
...
               end)
 
-            results =
-              changesets
-              |> Enum.map(fn changeset ->
-                identity =
-                  changeset.attributes
-                  |> Map.take(keys)
+            cant_map_results_to_changesets =
+              any_generated_keys_missing?(keys, resource, changesets)
```
Comment (zachdaniel) [inline lib/data_layer.ex]: but I don't see how this is possible? Don't we require the keys to be given to do an upsert on them? And this is only inside the upsert branch.

Comment (zachdaniel) [reply lib/data_layer.ex]: Oh, then we should switch back to index based when it's not an upsert. If it's just a create, either they are all created or not, there is no variability. Can you make that change?

**Review by zachdaniel — APPROVED** [review]
