### PR TITLE
Ignore module conflict when compiling migration file

### LINKED ISSUE #480: "redefining module" kind of warnings when using multi tenancy in tests
**Describe the bug**
I see `redefining module [...].Repo.TenantMigrations.AddCloakToFrontAndCustomerio (current version defined in memory)` kind of warnings when running tests for context-driven multi tenant resources. Any workarounds for these?

**To Reproduce**
Setup a project with context-driven multi tenancy and add test suite that creates different tenants across test files.

**Expected behavior**
No warnings during test run.

** Runtime
```
eden λ mix hex.outdated | grep ash
ash                     3.4.62   3.4.62   Up-to-date
ash_cloak               0.1.3    0.1.3    Up-to-date
ash_paper_trail         0.5.0    0.5.0    Up-to-date
ash_phoenix             2.1.17   2.1.18   Update possible
ash_postgres            2.5.1    2.5.1    Up-to-date
phoenix_live_dashboard  0.8.6    0.8.6    Up-to-date
```

**Additional context**
https://discord.com/channels/711271361523351632/1259099945366061110/1338844946337235058

### PR DESCRIPTION
**Pull request by smt116**
This fixes the problem of logging "redefining module" entries when using context-driven multitenancy (where each tenant tries to compile the migration module).

[Fixes #480]

### CODE REVIEW

File: lib/multitenancy.ex [hunk 1]
```diff
@@ -15,8 +15,6 @@ defmodule AshPostgres.MultiTenancy do
       migrations_path ||
         repo.config()[:tenant_migrations_path] || default_tenant_migration_path(repo)
 
-    Code.compiler_options(ignore_module_conflict: true)
```
Comment (smt116) [inline lib/multitenancy.ex:18]: This configuration is process-specific. It didn't work because `AshPostgres.MigrationCompileCache` uses an isolated agent abstraction.

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀
